// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calcpb/calc.proto

package calcpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	N1                   int32    `protobuf:"varint,1,opt,name=n1,proto3" json:"n1,omitempty"`
	N2                   int32    `protobuf:"varint,2,opt,name=n2,proto3" json:"n2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87762106ce7f1ca, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetN1() int32 {
	if m != nil {
		return m.N1
	}
	return 0
}

func (m *Request) GetN2() int32 {
	if m != nil {
		return m.N2
	}
	return 0
}

type Response struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a87762106ce7f1ca, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "calcpb.Request")
	proto.RegisterType((*Response)(nil), "calcpb.Response")
}

func init() { proto.RegisterFile("calcpb/calc.proto", fileDescriptor_a87762106ce7f1ca) }

var fileDescriptor_a87762106ce7f1ca = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbd, 0x4a, 0x04, 0x31,
	0x14, 0x85, 0x99, 0x51, 0xc7, 0xf1, 0x22, 0xab, 0x06, 0x91, 0x65, 0xb0, 0x90, 0x54, 0x2a, 0xee,
	0x84, 0x1d, 0xc1, 0xc2, 0xd2, 0x7d, 0x83, 0xd9, 0xce, 0x2e, 0x13, 0x42, 0x58, 0xc8, 0xe4, 0xc6,
	0xfc, 0x60, 0x6f, 0x67, 0xed, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x98, 0x04, 0x2c, 0x6c, 0xac, 0x0e,
	0xe7, 0xf0, 0x9d, 0xe4, 0xde, 0x0b, 0x67, 0x82, 0x6b, 0x61, 0x27, 0xf6, 0x23, 0xbd, 0x75, 0x18,
	0x90, 0x34, 0x39, 0xea, 0x2e, 0x15, 0xa2, 0xd2, 0x92, 0x71, 0xbb, 0x63, 0xdc, 0x18, 0x0c, 0x3c,
	0xec, 0xd0, 0xf8, 0x4c, 0x75, 0x77, 0x49, 0xc4, 0x4a, 0x49, 0xb3, 0xf2, 0xaf, 0x5c, 0x29, 0xe9,
	0x18, 0xda, 0x44, 0xfc, 0xa5, 0xe9, 0x0d, 0x1c, 0x8e, 0xf2, 0x25, 0x4a, 0x1f, 0xc8, 0x02, 0x6a,
	0xb3, 0x5e, 0x56, 0x57, 0xd5, 0xf5, 0xc1, 0x58, 0x9b, 0x75, 0xf2, 0xc3, 0xb2, 0x2e, 0x7e, 0xa0,
	0x14, 0xda, 0x51, 0x7a, 0x8b, 0xc6, 0x4b, 0x72, 0x01, 0x8d, 0x93, 0x3e, 0xea, 0x50, 0xf8, 0xe2,
	0x86, 0xf7, 0x0a, 0x60, 0xc3, 0xb5, 0x88, 0x9a, 0x07, 0x74, 0xe4, 0x01, 0xf6, 0xb6, 0x71, 0x26,
	0x27, 0x7d, 0x9e, 0xbc, 0x2f, 0x5f, 0x75, 0xa7, 0xbf, 0x41, 0x7e, 0x90, 0x1e, 0xbf, 0x7d, 0x7e,
	0x7d, 0xd4, 0x0d, 0xd9, 0x67, 0x3e, 0xce, 0x64, 0x03, 0xed, 0x36, 0x4e, 0xc1, 0x71, 0x11, 0xfe,
	0x53, 0x3e, 0x4f, 0xe5, 0x05, 0x3d, 0x62, 0xbe, 0xb4, 0x1e, 0xab, 0xdb, 0xa7, 0xf6, 0xb9, 0x1c,
	0x6c, 0x6a, 0xd2, 0xae, 0xf7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x22, 0xa8, 0x78, 0x54,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorClient interface {
	Sum(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Subtract(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type calculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculatorClient(cc grpc.ClientConnInterface) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Sum(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/calcpb.Calculator/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorClient) Subtract(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/calcpb.Calculator/Subtract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServer is the server API for Calculator service.
type CalculatorServer interface {
	Sum(context.Context, *Request) (*Response, error)
	Subtract(context.Context, *Request) (*Response, error)
}

// UnimplementedCalculatorServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (*UnimplementedCalculatorServer) Sum(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedCalculatorServer) Subtract(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subtract not implemented")
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calcpb.Calculator/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Sum(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calculator_Subtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Subtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calcpb.Calculator/Subtract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Subtract(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calcpb.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _Calculator_Sum_Handler,
		},
		{
			MethodName: "Subtract",
			Handler:    _Calculator_Subtract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calcpb/calc.proto",
}
